Misc. updates

diff --git a/scripts/serve-docs b/scripts/serve-docs
--- a/scripts/serve-docs
+++ b/scripts/serve-docs
@@ -6,5 +6,6 @@ if [ -n "$dir" ]; then
   cd "dist-newstyle/src/$(basename "$dir")"
   nix develop --command "serve-docs"
 else
-  echo "Error: plutus-apps directory not found"
+  >&2 echo "Error: plutus-apps directory not found"
+  exit 1
 fi
